SV_SYNTH_SOURCES=system/System.sv
VERILOG_SYNTH_SOURCE=system/System.v

TOP_MODULE_RESOURCE_CHECK=SystemDemo
TOP_MODULE_DEMO=SystemDemo
CONSTRAINTS=../common/constraints/ulx3s.lpf

include ../common/make/fpga.mk
