# source verilog files
SYNTH_SOURCES=rca.sv
TOP_SYNTH_MODULE=rca4_demo

# zip file that gets uploaded
ZIP_SOURCES=rca.sv fpga_build/rca4_demo.bit
ZIP_FILE=rca.zip

CONSTRAINTS=hw1.lpf

include ../common/make/fpga.mk
