SYNTH_SOURCES=System.v

TOP_SYNTH_MODULE=System
CONSTRAINTS=system/board.lpf

ZIP_SOURCES=DatapathAxilMemory.sv ../hw2b/cla.sv ../hw4-multicycle/divider_unsigned_pipelined.sv
ZIP_FILE=axilmem.zip

include ../common/make/fpga.mk
