# NB: this container image is the exact one used by the Gradescope
# autograder. It is x86-only, however, and thus incurs ISA translation overheads
# on Apple Silicon.

FROM gradescope/autograder-base:ubuntu-22.04-jdk17 AS base

RUN apt-get update
RUN apt-get install --yes sudo git zip tmux emacs time
RUN apt-get install --yes gcc-riscv64-linux-gnu

# gem5 dependencies
RUN apt-get install --yes build-essential git m4 scons zlib1g zlib1g-dev \
    libprotobuf-dev protobuf-compiler libprotoc-dev libgoogle-perftools-dev \
    python3-dev libboost-all-dev pkg-config python3-tk clang-format-15
# Configure clang-format-15 and git-clang-format-15 as the system defaults.
RUN update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-15 150 \
        --slave /usr/bin/clang-format-diff clang-format-diff /usr/bin/clang-format-diff-15 \
        --slave /usr/bin/git-clang-format git-clang-format /usr/bin/git-clang-format-15

# [Optional] Add other alternative versions, and select version 15 as the default version.
# RUN update-alternatives --config clang-format

WORKDIR /
RUN git clone https://github.com/gem5/gem5
WORKDIR /gem5
RUN pip install -r requirements.txt
RUN yes | scons build/RISCV/gem5.fast

CMD ["/bin/bash"]
