SYNTH_SOURCES=DatapathSingleCycle.sv
TOP_SYNTH_MODULE=RiscvProcessor

ZIP_SOURCES=DatapathSingleCycle.sv ../hw2a-divider/divider_unsigned.sv ../hw2b-cla/cla.sv fpga_build/resource-report.json
ZIP_FILE=single.zip

include ../common/make/fpga.mk
