`default_nettype none
`timescale 1ns / 1ps

// registers are 32 bits in RV32
`define REG_SIZE 31:0

// insns are 32 bits in RV32IM
`define INSN_SIZE 31:0

`define RESP_OK 2'b00

// determine HDMI output resolution, choose one and only one
//`define HDMI_1280 // 1280x720 resolution
`define HDMI_800  // 800x600 resolution
//`define HDMI_640  // 640x480 resolution

`ifdef SYNTHESIS
`include "MyClockGen.v"
`endif

`include "DatapathPipelinedAxil.sv"
`include "system/usb/usb_hid_host.v"
`include "../hw3-singlecycle/system/debouncer.v"

`ifdef HDMI_1280
`include "system/hdmi_1280_720/dvi_generator.sv"
`include "system/hdmi_1280_720/simple_720p.sv"
`include "system/hdmi_1280_720/tmds_encoder_dvi.sv"
`include "system/hdmi_1280_720/hdmi_video.sv"
`endif
`ifdef HDMI_800
`include "system/hdmi_800_600/dvi_generator.sv"
`include "system/hdmi_800_600/simple_800_600.sv"
`include "system/hdmi_800_600/tmds_encoder_dvi.sv"
`include "system/hdmi_800_600/hdmi_video.sv"
`endif
`ifdef HDMI_640
`include "system/hdmi_640_480/hdmi_video.v"
`include "system/hdmi_640_480/vga_video.v"
`include "system/hdmi_640_480/vga2dvid.v"
`include "system/hdmi_640_480/fake_differential.v"
`include "system/hdmi_640_480/tmds_encoder.v"
`endif

// FULL_SIZE_MEM means 32KB memory, non-FULL_SIZE means 2KB memory
`define FULL_SIZE_MEM
// FULL_SIZE_FRAME_BUFFER means 400x300 frame buffer, non-FULL_SIZE means 40x30 frame buffer
`define FULL_SIZE_FRAME_BUFFER

module SystemResourceCheck (
    input wire external_clk_25MHz,
    input wire [6:0] btn,
    output wire [7:0] led
);

wire clk, clk_locked, ignore0, ignore1;
MyClockGen clock_gen (
  .input_clk_25MHz(external_clk_25MHz),
  .clk_125MHz(ignore0),
  .clk_25MHz(ignore1),
  .clk_proc(clk),
  .locked(clk_locked)
);
wire rst = !clk_locked;

// memory is dual-ported, to connect to both datapath and D$
axil_if axil_mem_ro ();
axil_if axil_mem_rw ();

EasyAxilMemory #(
	   .OPT_SKIDBUFFER(1),
	   .OPT_LOWPOWER(0),
     .NUM_WORDS(128)
) memory (
	      .ACLK(clk),
	      .ARESETn(~rst),
	      .port_rw(axil_mem_rw.subord),
        .port_ro(axil_mem_ro.subord)
	      );

  // NB: must connect all ports to avoid sv2v implicit net errors (due to `default_nettype none)
  wire [`REG_SIZE] trace_completed_pc;
  wire [`INSN_SIZE] trace_completed_insn;
  cycle_status_e trace_completed_cycle_status;
  DatapathPipelinedAxil datapath (
      .clk(clk),
      .rst(rst),
      .imem(axil_mem_ro.manager),
      .dmem(axil_mem_rw.manager),
      .halt(led[0]),
      .*
  );
endmodule

/** NB: this module was generated by ecppll, do not edit manually */
module DemoClockGen
(
    input input_clk_25MHz, // 25 MHz, 0 deg
    output clk_125MHz, // 125 MHz, 0 deg
    output clk_25MHz, // 25 MHz, 0 deg
    output clk_12MHz, // 12.0192 MHz, 0 deg
    output locked
);
wire clkfb;
(* FREQUENCY_PIN_CLKI="25" *)
(* FREQUENCY_PIN_CLKOP="125" *)
(* FREQUENCY_PIN_CLKOS="25" *)
(* FREQUENCY_PIN_CLKOS2="12.0192" *)
(* ICP_CURRENT="12" *) (* LPF_RESISTOR="8" *) (* MFG_ENABLE_FILTEROPAMP="1" *) (* MFG_GMCREF_SEL="2" *)
EHXPLLL #(
        .PLLRST_ENA("DISABLED"),
        .INTFB_WAKE("DISABLED"),
        .STDBY_ENABLE("DISABLED"),
        .DPHASE_SOURCE("DISABLED"),
        .OUTDIVIDER_MUXA("DIVA"),
        .OUTDIVIDER_MUXB("DIVB"),
        .OUTDIVIDER_MUXC("DIVC"),
        .OUTDIVIDER_MUXD("DIVD"),
        .CLKI_DIV(1),
        .CLKOP_ENABLE("ENABLED"),
        .CLKOP_DIV(5),
        .CLKOP_CPHASE(2),
        .CLKOP_FPHASE(0),
        .CLKOS_ENABLE("ENABLED"),
        .CLKOS_DIV(25),
        .CLKOS_CPHASE(2),
        .CLKOS_FPHASE(0),
        .CLKOS2_ENABLE("ENABLED"),
        .CLKOS2_DIV(52),
        .CLKOS2_CPHASE(2),
        .CLKOS2_FPHASE(0),
        .FEEDBK_PATH("INT_OP"),
        .CLKFB_DIV(5)
    ) pll_i (
        .RST(1'b0),
        .STDBY(1'b0),
        .CLKI(input_clk_25MHz),
        .CLKOP(clk_125MHz),
        .CLKOS(clk_25MHz),
        .CLKOS2(clk_12MHz),
        .CLKFB(clkfb),
        .CLKINTFB(clkfb),
        .PHASESEL0(1'b0),
        .PHASESEL1(1'b0),
        .PHASEDIR(1'b1),
        .PHASESTEP(1'b1),
        .PHASELOADREG(1'b1),
        .PLLWAKESYNC(1'b0),
        .ENCLKOP(1'b0),
        .LOCK(locked)
	);
endmodule

module hdmi1280_clock_gen #(
    parameter CLKI_DIV  = 1,     // input clock divider
    parameter CLKFB_DIV = 1,     // feedback divider
    parameter CLKOP_DIV = 1,     // primary output clock divider
    parameter CLKOP_CPHASE = 0,  // primary output clock phase
    parameter CLKOS_DIV = 1,     // secondary output clock divider
    parameter CLKOS_CPHASE = 0   // secondary output clock phase
    ) (
    input  wire clk_in,      // input clock
    output wire clk_5x_out,  // output 5x clock
    output wire clk_out,     // output clock
    output reg  clk_locked   // clock locked?
    );

    wire locked;  // unsynced lock signal
    wire ignore;

    // HDL attributes (values are from Project Trellis)
    (* ICP_CURRENT="12" *)
    (* LPF_RESISTOR="8" *)
    (* MFG_ENABLE_FILTEROPAMP="1" *)
    (* MFG_GMCREF_SEL="2" *)

    EHXPLLL #(
        .PLLRST_ENA("DISABLED"),
        .INTFB_WAKE("DISABLED"),
        .STDBY_ENABLE("DISABLED"),
        .DPHASE_SOURCE("DISABLED"),
        .OUTDIVIDER_MUXA("DIVA"),
        .OUTDIVIDER_MUXB("DIVB"),
        .OUTDIVIDER_MUXC("DIVC"),
        .OUTDIVIDER_MUXD("DIVD"),
        .CLKI_DIV(CLKI_DIV),
        .CLKOP_ENABLE("ENABLED"),
        .CLKOP_DIV(CLKOP_DIV),
        .CLKOP_CPHASE(CLKOP_CPHASE),
        .CLKOP_FPHASE(0),
        .CLKOS_ENABLE("ENABLED"),
        .CLKOS_DIV(CLKOS_DIV),
        .CLKOS_CPHASE(CLKOS_CPHASE),
        .CLKOS_FPHASE(0),
        .FEEDBK_PATH("CLKOP"),
        .CLKFB_DIV(CLKFB_DIV)
    ) pll_i (
        .RST(1'b0),
        .STDBY(1'b0),
        .CLKI(clk_in),
        .CLKOP(clk_5x_out),
        .CLKOS(clk_out),
        .CLKFB(clk_5x_out),
        .CLKINTFB(ignore),
        .PHASESEL0(1'b0),
        .PHASESEL1(1'b0),
        .PHASEDIR(1'b1),
        .PHASESTEP(1'b1),
        .PHASELOADREG(1'b1),
        .PLLWAKESYNC(1'b0),
        .ENCLKOP(1'b0),
        .LOCK(locked)
    );

    // ensure clock lock is synced with output clock
    reg locked_sync;
    always @(posedge clk_out) begin
        locked_sync <= locked;
        clk_locked <= locked_sync;
    end
endmodule

module hdmi800_clock_gen (
    input input_clk_25MHz, // 25 MHz, 0 deg
    output clk_200MHz,     // 200 MHz, 0 deg
    output clk_40MHz,      // 40 MHz, 0 deg
    output clk_locked
);
wire clkfb, locked;
(* FREQUENCY_PIN_CLKI="25" *)
(* FREQUENCY_PIN_CLKOP="200" *)
(* FREQUENCY_PIN_CLKOS="40" *)
(* ICP_CURRENT="12" *) (* LPF_RESISTOR="8" *) (* MFG_ENABLE_FILTEROPAMP="1" *) (* MFG_GMCREF_SEL="2" *)
EHXPLLL #(
        .PLLRST_ENA("DISABLED"),
        .INTFB_WAKE("DISABLED"),
        .STDBY_ENABLE("DISABLED"),
        .DPHASE_SOURCE("DISABLED"),
        .OUTDIVIDER_MUXA("DIVA"),
        .OUTDIVIDER_MUXB("DIVB"),
        .OUTDIVIDER_MUXC("DIVC"),
        .OUTDIVIDER_MUXD("DIVD"),
        .CLKI_DIV(1),
        .CLKOP_ENABLE("ENABLED"),
        .CLKOP_DIV(3),
        .CLKOP_CPHASE(1),
        .CLKOP_FPHASE(0),
        .CLKOS_ENABLE("ENABLED"),
        .CLKOS_DIV(15),
        .CLKOS_CPHASE(1),
        .CLKOS_FPHASE(0),
        .FEEDBK_PATH("INT_OP"),
        .CLKFB_DIV(8)
    ) pll_i (
        .RST(1'b0),
        .STDBY(1'b0),
        .CLKI(input_clk_25MHz),
        .CLKOP(clk_200MHz),
        .CLKOS(clk_40MHz),
        .CLKFB(clkfb),
        .CLKINTFB(clkfb),
        .PHASESEL0(1'b0),
        .PHASESEL1(1'b0),
        .PHASEDIR(1'b1),
        .PHASESTEP(1'b1),
        .PHASELOADREG(1'b1),
        .PLLWAKESYNC(1'b0),
        .ENCLKOP(1'b0),
        .LOCK(locked)
	);

    // ensure clock lock is synced with output clock
    reg locked_sync;
    always @(posedge clk_40MHz) begin
        locked_sync <= locked;
        clk_locked <= locked_sync;
    end
endmodule


module MemoryMap (
    input wire ACLK,
    input wire ARESETn,
    axil_if.subord proc,
    axil_if.manager cache,
    input wire clk_25MHz,
    input wire clk_125MHz,
    input wire clk_12MHz,
    input wire clk_locked,
    input wire [6:0] btn,
    output wire [7:0] led,
    output wire [3:0] gpdi_dp,
    output wire [3:0] gpdi_dn,
    inout wire usb_fpga_bd_dn,
    inout wire usb_fpga_bd_dp
);

  // This module is a "bump on the wire", a (conceptually) combinational circuit between proc and cache.

  localparam int MmapButtons      = 32'hFF00_1000;
  localparam int MmapLeds         = 32'hFF00_2000;
  //localparam int MmapUartRead   = 32'hFF00_3000;
  //localparam int MmapUartWrite  = 32'hFF00_3001;
  localparam int MmapUsb          = 32'hFF00_4000;
  localparam int MmapRng          = 32'hFF00_5000;
  localparam int MmapDisplayStart = 32'hFF10_0000;

  `ifdef FULL_SIZE_FRAME_BUFFER
  localparam bit[9:0] DisplayWidth = 400;
  localparam bit[9:0] DisplayHeight = 300;
  `else
  localparam bit[9:0] DisplayWidth = 40;
  localparam bit[9:0] DisplayHeight = 30;
  `endif

  localparam int DisplayPixels = DisplayHeight * DisplayWidth;
  localparam int DisplayPixelSizeBits = 8;

  `ifdef HDMI_1280
  localparam int HdmiWidth = 1280;
  localparam int HdmiHeight = 720;
  localparam int DisplayScaleFactor = (HdmiWidth / {22'd0, DisplayWidth}) / 2;
  `endif
  `ifdef HDMI_800
  localparam int HdmiWidth = 800;
  localparam int HdmiHeight = 600;
  localparam int DisplayScaleFactor = HdmiWidth / DisplayWidth;
  `endif
  `ifdef HDMI_640
  localparam int HdmiWidth = 640;
  localparam int HdmiHeight = 480;
  localparam int DisplayScaleFactor = HdmiWidth / DisplayWidth;
  `endif

  localparam int DisplayFrameBufferScaleShift = $clog2(DisplayScaleFactor);
  localparam int MmapDisplayEnd = MmapDisplayStart + (DisplayPixels * (DisplayPixelSizeBits / 8));

  localparam bit True = 1'b1;
  localparam bit False = 1'b0;

  // wire [7:0] fake_led;
  // wire proc_led_write = proc.AWADDR == MmapLeds && proc.AWVALID && proc.WVALID && |proc.WSTRB && |proc.WDATA[7:0];
  // wire [7:0] ewnz_trace = {
  //   proc_led_write,
  //   cache.AWREADY && cache.WREADY,
  //   proc_led_write && cache.AWREADY,
  //   proc_led_write && cache.WREADY,
  //   proc_led_write && cache.AWREADY && cache.WREADY,
  //   2'b11,
  //   // was_axi_write,
  //   // was_led,
  //   // was_write,
  //   // is_axi_write,
  //   // is_led,
  //   // is_write,
  //   // was_led && (|last_wdata[7:0]),
  //   1'b1
  // };
  // Ewnz wnz (
  //   .clk(ACLK),
  //   .rst(~ARESETn),
  //   .signals(ewnz_trace),
  //   .ewnz(fake_led)
  // );

  assign cache.ARADDR = proc.ARADDR;
  assign cache.ARVALID = is_read ? False : proc.ARVALID;  // hide request from the cache
  assign cache.ARPROT = proc.ARPROT;
  assign proc.ARREADY = cache.ARREADY;
  assign cache.RREADY = proc.RREADY;
  assign proc.RVALID = was_read ? True : cache.RVALID;
  assign proc.RDATA =
    was_board_button ? {{proc.ADDR_WIDTH - 7{1'b0}}, btn} :
    was_usb ? {{proc.DATA_WIDTH - 10{1'b0}}, usb_buttons} :
    was_rng ? rng_state : cache.RDATA;
  assign proc.RRESP = cache.RRESP;

  assign cache.AWADDR = proc.AWADDR;

  assign cache.AWVALID = is_write ? False : proc.AWVALID;  // hide request from the cache
  assign cache.WVALID = is_write ? False : proc.WVALID;
  assign proc.AWREADY = cache.AWREADY;
  assign cache.AWPROT = proc.AWPROT;
  assign cache.WDATA = proc.WDATA;
  assign cache.WSTRB = proc.WSTRB;
  assign proc.WREADY = cache.WREADY;
  assign cache.BREADY = proc.BREADY;
  assign proc.BVALID = was_write ? True : cache.BVALID;
  assign proc.BRESP = cache.BRESP;

  logic [proc.ADDR_WIDTH-1:0] last_araddr, last_awaddr;
  logic [proc.DATA_WIDTH-1:0] last_wdata;
  logic [(proc.DATA_WIDTH/8)-1:0] last_wstrb;
  logic last_arvalid, last_arready, last_awvalid, last_awready, last_wvalid, last_wready;

  wire is_axi_read = proc.ARVALID && cache.ARREADY;
  wire is_board_button = is_axi_read && (proc.ARADDR == MmapButtons);
  wire is_usb = is_axi_read && (proc.ARADDR == MmapUsb);
  wire is_rng = is_axi_read && (proc.ARADDR == MmapRng);
  wire is_read = is_board_button || is_usb || is_rng;
  wire was_axi_read = last_arvalid && last_arready;
  wire was_board_button = was_axi_read && (last_araddr == MmapButtons);
  wire was_usb = was_axi_read && (last_araddr == MmapUsb);
  wire was_rng = was_axi_read && (last_araddr == MmapRng);
  wire was_read = was_board_button || was_usb || was_rng;

  wire is_axi_write = proc.AWVALID && cache.AWREADY && proc.WVALID && cache.WREADY;
  wire is_led = is_axi_write && (proc.AWADDR == MmapLeds);
  wire is_hdmi = is_axi_write && (MmapDisplayStart <= proc.AWADDR && proc.AWADDR < MmapDisplayEnd);
  wire is_write = is_led || is_hdmi;
  wire was_axi_write = last_awvalid && last_awready && last_wvalid && last_wready;
  wire was_led = was_axi_write && (last_awaddr == MmapLeds);
  wire was_hdmi = was_axi_write && (MmapDisplayStart <= last_awaddr && last_awaddr < MmapDisplayEnd);
  wire was_write = was_led || was_hdmi;

  always_ff @(posedge ACLK) begin
    if (!ARESETn) begin
      last_araddr  <= 0;
      last_arvalid <= False;
      last_arready <= False;

      last_awaddr  <= 0;
      last_awvalid <= False;
      last_awready <= False;
      last_wdata   <= 0;
      last_wstrb   <= 0;
      last_wvalid  <= False;
      last_wready  <= False;
    end else begin
      last_araddr  <= proc.ARADDR;
      last_arvalid <= proc.ARVALID;
      last_arready <= cache.ARREADY;

      last_awaddr  <= proc.AWADDR;
      last_awvalid <= proc.AWVALID;
      last_awready <= cache.AWREADY;
      last_wdata   <= proc.WDATA;
      last_wstrb   <= proc.WSTRB;
      last_wvalid  <= proc.WVALID;
      last_wready  <= cache.WREADY;
    end
  end

  // NB: Buttons are implemented above as mux on RDATA

  // Random Number Generator: a linear-feedback shift register

  logic [31:0] rng_state;
  logic feedback;
  always_ff @(posedge ACLK) begin
    if (!ARESETn) begin
      rng_state <= 12345;
    end else begin
      feedback <= rng_state[0] ^ rng_state[1] ^ rng_state[21] ^ rng_state[31]; // XOR taps
      rng_state <= {rng_state[30:0], feedback}; // Shift left and insert feedback
    end
  end

  // LEDs

  logic [7:0] led_state;
  assign led = led_state;
  always_ff @(posedge ACLK) begin
    if (!ARESETn) begin
      led_state <= 0;
    end else begin
      if (was_led) begin
        led_state <= last_wdata[7:0];
      end
    end
  end

  // USB

  wire [1:0] usb_type;
  wire [7:0] key_modifiers, key1, key2, key3, key4;
  wire [7:0] mouse_btn;
  wire signed [7:0] mouse_dx, mouse_dy;
  wire [63:0] hid_report;
  wire usb_report, usb_conerr;
  wire game_l, game_r, game_u, game_d, game_a, game_b, game_x, game_y;
  wire game_select, game_start;
  wire [9:0] usb_buttons = {
    game_l, game_r, game_u, game_d, game_a, game_b, game_x, game_y, game_select, game_start
  };

`ifdef SYNTHESIS
  usb_hid_host usb (
      .usbclk(clk_12MHz),
      .usbrst_n(ARESETn),
      .usb_dm(usb_fpga_bd_dn),
      .usb_dp(usb_fpga_bd_dp),
      .typ(usb_type),
      .report(usb_report),
      .key_modifiers(key_modifiers),
      .key1(key1),
      .key2(key2),
      .key3(key3),
      .key4(key4),
      .mouse_btn(mouse_btn),
      .mouse_dx(mouse_dx),
      .mouse_dy(mouse_dy),
      .game_l(game_l),
      .game_r(game_r),
      .game_u(game_u),
      .game_d(game_d),
      .game_a(game_a),
      .game_b(game_b),
      .game_x(game_x),
      .game_y(game_y),
      .game_sel(game_select),
      .game_sta(game_start),
      .conerr(usb_conerr),
      .dbg_hid_report(hid_report)
  );
`endif

  // HDMI display frame buffer

//   localparam bit [7:0] Black = 8'b000_000_00; // 8'h00
//   localparam bit [7:0] Red   = 8'b111_000_00; // 8'hE0
  // localparam bit [7:0] White = 8'b111_111_11; // 8'hFF
  // localparam bit [7:0] Teal  = 8'b000_111_10; // 8'h1E

  logic [DisplayPixelSizeBits-1:0] frame_buffer[DisplayWidth * DisplayHeight];

  logic [proc.ADDR_WIDTH-1:0] fb_write_addr;
  logic [DisplayPixelSizeBits-1:0] fb_write_data;
  always_comb begin
      fb_write_addr = '0;
      fb_write_data = '0;

      case (last_wstrb)
      4'b0001: begin
          fb_write_addr = last_awaddr - MmapDisplayStart;
          fb_write_data = last_wdata[7:0];
      end
      4'b0010: begin
          fb_write_addr = (last_awaddr - MmapDisplayStart) + 1;
          fb_write_data = last_wdata[15:8];
      end
      4'b0100: begin
          fb_write_addr = (last_awaddr - MmapDisplayStart) + 2;
          fb_write_data = last_wdata[23:16];
      end
      4'b1000: begin
          fb_write_addr = (last_awaddr - MmapDisplayStart) + 3;
          fb_write_data = last_wdata[31:24];
      end
      default: begin end
      endcase
  end

  logic [proc.ADDR_WIDTH-1:0] fb_write_addr_reg;
  logic [DisplayPixelSizeBits-1:0] fb_write_data_reg;
  always_ff @(posedge ACLK) begin
    if (!ARESETn) begin
      fb_write_addr_reg <= 0;
      fb_write_data_reg <= 0;
    end else if (was_hdmi) begin
      fb_write_addr_reg <= fb_write_addr;
      fb_write_data_reg <= fb_write_data;
      frame_buffer[fb_write_addr_reg] <= fb_write_data_reg;
    end
  end

`ifdef HDMI_1280
  wire [11:0] raw_x, raw_y, raw_x_scaled, raw_y_scaled;
  assign raw_x_scaled = raw_x >> DisplayFrameBufferScaleShift;
  assign raw_y_scaled = raw_y >> DisplayFrameBufferScaleShift;
  wire [9:0] x = raw_x_scaled < {2'd0, DisplayWidth} ? raw_x_scaled[9:0] : DisplayWidth - 1;
  wire [8:0] y = raw_y_scaled < {2'd0, DisplayHeight} ? raw_y_scaled[8:0] : DisplayHeight - 1;
`endif
`ifdef HDMI_800
  wire [11:0] raw_x, raw_y, raw_x_scaled, raw_y_scaled;
  assign raw_x_scaled = raw_x >> DisplayFrameBufferScaleShift;
  assign raw_y_scaled = raw_y >> DisplayFrameBufferScaleShift;
  wire [9:0] x = raw_x_scaled < {2'd0, DisplayWidth} ? raw_x_scaled[9:0] : DisplayWidth - 1;
  wire [8:0] y = raw_y_scaled < {2'd0, DisplayHeight} ? raw_y_scaled[8:0] : DisplayHeight - 1;
`endif
`ifdef HDMI_640
  wire [9:0] raw_x, raw_y, raw_x_scaled, raw_y_scaled;
  assign raw_x_scaled = raw_x >> DisplayFrameBufferScaleShift;
  assign raw_y_scaled = raw_y >> DisplayFrameBufferScaleShift;
  wire [9:0] x = raw_x_scaled < DisplayWidth ? raw_x_scaled : DisplayWidth - 1;
  wire [8:0] y = raw_y_scaled < DisplayHeight ? raw_y_scaled[8:0] : DisplayHeight - 1;
`endif

`ifdef FULL_SIZE_FRAME_BUFFER
  // NB: use this for 400x300 display
  wire [16:0] fb_index = ({8'd0, y} * {7'd0, DisplayWidth}) + {7'd0, x};
  logic [16:0] fb_index_reg;
`else
  // NB: use this for 40x30 display
  wire [10:0] fb_index = ({2'd0, y} * {1'd0, DisplayWidth}) + {1'd0, x};
  logic [10:0] fb_index_reg;
`endif

  logic [DisplayPixelSizeBits-1:0] color8;
  // scale from 8-bit color to 24-bit color
  wire [7:0] red8   = {color8[7:5], color8[7:5], color8[7:6]};
  wire [7:0] green8 = {color8[4:2], color8[4:2], color8[4:3]};
  wire [7:0] blue8  = {color8[1:0], color8[1:0], color8[1:0], color8[1:0]};

  wire [23:0] color24 = {red8, green8, blue8};
`ifdef SYNTHESIS
`ifdef HDMI_1280
  // generate pixel clock
  logic clk_pix;
  logic clk_pix_5x;
  logic clk_pix_locked;
  hdmi1280_clock_gen #(  // 74 MHz (PLL can't do exact 74.25 MHz for 720p)
      .CLKI_DIV(5),
      .CLKFB_DIV(74),
      .CLKOP_DIV(2),
      .CLKOP_CPHASE(1),
      .CLKOS_DIV(10),
      .CLKOS_CPHASE(5)
  ) hdmi_clock_gen_inst (
      .clk_in(clk_25MHz),
      .clk_5x_out(clk_pix_5x),
      .clk_out(clk_pix),
      .clk_locked(clk_pix_locked)
  );

  always_ff @(posedge clk_pix) begin
    if (!clk_pix_locked) begin
      color8 <= 0;
      fb_index_reg <= 0;
    end else begin
      fb_index_reg <= fb_index;
      color8 <= frame_buffer[fb_index_reg];
    end
  end

  hdmi_video hdmi_video (
    .clk_pix,
    .clk_pix_5x,
    .clk_pix_locked,
    .gpdi_dp,
    .sx(raw_x),
    .sy(raw_y),
    .pixel_r(red8),
    .pixel_g(green8),
    .pixel_b(blue8)
  );
`endif
`ifdef HDMI_800
  // generate pixel clock
  logic clk_pix;
  logic clk_pix_5x;
  logic clk_pix_locked;
  hdmi800_clock_gen hdmi_clock_gen_inst (
       .input_clk_25MHz(clk_25MHz),
       .clk_200MHz(clk_pix_5x),
       .clk_40MHz(clk_pix),
       .clk_locked(clk_pix_locked)
    );

  always_ff @(posedge clk_pix) begin
    if (!clk_pix_locked) begin
      color8 <= 0;
      fb_index_reg <= 0;
    end else begin
      fb_index_reg <= fb_index;
      color8 <= frame_buffer[fb_index_reg];
    end
  end

  hdmi_video hdmi_video (
    .clk_pix,
    .clk_pix_5x,
    .clk_pix_locked,
    .gpdi_dp,
    .sx(raw_x),
    .sy(raw_y),
    .pixel_r(red8),
    .pixel_g(green8),
    .pixel_b(blue8)
  );
`endif
`ifdef HDMI_640
  always_ff @(posedge clk_25MHz) begin
    if (!ARESETn) begin // TODO: this reset signal is not synchronous wrt clk_25MHz...
      color8 <= 0;
      fb_index_reg <= 0;
    end else begin
      fb_index_reg <= fb_index;
      color8 <= frame_buffer[fb_index_reg]; // fbread
    end
  end

  hdmi_video hdmi_video (
      .clk_25MHz(clk_25MHz),
      .clk_125MHz(clk_125MHz),
      .clk_locked(clk_locked),
      .x(raw_x),
      .y(raw_y),
      .color(color24),
      .gpdi_dp(gpdi_dp),
      .gpdi_dn(gpdi_dn)
  );
`endif
`endif

endmodule

// Just the frame buffer, for debugging
module SystemDemo_fbonly (
  input wire external_clk_25MHz,
  input wire [6:0] btn,
  output wire [7:0] led,
  output wire [3:0] gpdi_dp,
  output wire [3:0] gpdi_dn
);
  localparam bit[9:0] DisplayWidth = 400;
  localparam bit[9:0] DisplayHeight = 300;
  localparam int HdmiWidth = 800;
  localparam int HdmiHeight = 600;
  localparam int DisplayScaleFactor = HdmiWidth / DisplayWidth;
  localparam int DisplayFrameBufferScaleShift = $clog2(DisplayScaleFactor);

  logic [7:0] frame_buffer[DisplayWidth * DisplayHeight];

  wire clk_proc, clk_locked;
  MyClockGen clock_gen (
    .input_clk_25MHz(external_clk_25MHz),
    .clk_proc(clk_proc),
    .locked(clk_locked)
  );

  wire demo_clocks_locked, clk_125MHz, clk_12MHz, clk_25MHz;
  DemoClockGen demo_clock_gen (
    .input_clk_25MHz(external_clk_25MHz),
    .locked(demo_clocks_locked),
    .clk_125MHz(clk_125MHz),
    .clk_25MHz(clk_25MHz),
    .clk_12MHz(clk_12MHz)
  );

  // initial begin
  //   for (integer i = 0; i < DisplayPixels; i = i + 1) begin
  //       frame_buffer[i] = White;
  //   end
  // end

  logic [31:0] fb_write_addr, fb_write_data, fb_write_addr_reg;

  assign fb_write_addr = {btn[6:0], btn[6:0], btn[6:0], btn[6:0], btn[3:0]};
  assign fb_write_data = {btn[6:0], btn[6:0], btn[6:0], btn[6:0], btn[3:0]};

  // FB write
  always_ff @(posedge clk_proc) begin
    if (!clk_locked) begin
      fb_write_addr_reg <= 0;
    end else begin
      fb_write_addr_reg <= fb_write_addr;
      frame_buffer[fb_write_addr_reg] <= fb_write_data; // fbwrite
    end
  end

  // FB read
  wire clk_pix = external_clk_25MHz;
  wire [7:0] color8;
  // logic [31:0] fb_index;
  // assign fb_index = {btn[6:0], btn[6:0], btn[6:0], btn[6:0], btn[3:0]};
  // NB: no registered outputs for FB read, HDMI controller needs the pixel this cycle
  always_ff @(posedge clk_pix) begin
    if (clk_locked) begin
      color8 <= frame_buffer[fb_index];
    end
  end

  wire [9:0] raw_x, raw_y, raw_x_scaled, raw_y_scaled;
  assign raw_x_scaled = raw_x >> DisplayFrameBufferScaleShift;
  assign raw_y_scaled = raw_y >> DisplayFrameBufferScaleShift;
  wire [9:0] x = raw_x_scaled < DisplayWidth ? raw_x_scaled : DisplayWidth - 1;
  wire [8:0] y = raw_y_scaled < DisplayHeight ? raw_y_scaled[8:0] : DisplayHeight - 1;
  wire [16:0] fb_index = ({8'd0, y} * {7'd0, DisplayWidth}) + {7'd0, x};

  // scale from 8-bit color to 24-bit color
  wire [7:0] red8   = {color8[7:5], color8[7:5], color8[7:6]};
  wire [7:0] green8 = {color8[4:2], color8[4:2], color8[4:3]};
  wire [7:0] blue8  = {color8[1:0], color8[1:0], color8[1:0], color8[1:0]};

  wire [23:0] color24 = {red8, green8, blue8};

`ifdef HDMI_640
  hdmi_video hdmi_video (
      .clk_25MHz(clk_25MHz),
      .clk_125MHz(clk_125MHz),
      .clk_locked(clk_locked),
      .x(raw_x),
      .y(raw_y),
      .color(color24),
      .gpdi_dp(gpdi_dp),
      .gpdi_dn(gpdi_dn)
  );
`endif
endmodule

// TODO: parameterize scan chain size
// module JtagScanChain (
//   input wire jtag_tck,
//   input wire jtag_tms,
//   input wire jtag_tdi,
//   output wire jtag_tdo,
//   input logic [31:0] in0
// );
//   // JTAG Primitive Signals
//   logic jtck, jtdi, jtdo1, jce1, jshift, jupdate;

//   JTAGG jtag_inst (
//     .TCK(jtag_tck),
//     .TMS(jtag_tms),
//     .TDI(jtag_tdi),
//     .TDO(jtag_tdo),
//     .JTDO1(jtdo1),    // input
//     .JTCK(jtck),      // output
//     .JTDI(jtdi),      // output
//     .JCE1(jce1),      // output
//     .JSHIFT(jshift),  // output
//     .JUPDATE(jupdate) // output
//   );

//   // The Scan Chain
//   logic [31:0] scan_chain_reg;

//   always_ff @(posedge jtck) begin
//     if (jce1) begin
//       if (jupdate) begin
//         // CAPTURE: Snap both registers into the chain at once
//         scan_chain_reg <= in0;
//       end
//     else if (jshift) begin
//       // SHIFT: Move everything toward TDO
//       // Input new data from TDI (allows writing while reading!)
//       scan_chain_reg <= {jtdi, scan_chain_reg[31:1]};
//     end
//     end
//   end

//   // Connect the end of the chain to the JTAG TDO pin
//   assign jtdo1 = scan_chain_reg[0];

// endmodule

/** shows on the LEDs whether each bit of `signals` Ever Was Non-Zero */
module Ewnz (
    input wire clk,
    input wire rst,
    input wire [7:0] signals,
    output wire [7:0] ewnz
);
  localparam bit True = 1'b1;

  logic [7:0] sticky_bits;
  assign ewnz = sticky_bits;

  always_ff @(posedge clk) begin
    if (rst) begin
        sticky_bits <= 0;
    end else /*if (init_done)*/ begin
        if (signals[0]) sticky_bits[0] <= True;
        if (signals[1]) sticky_bits[1] <= True;
        if (signals[2]) sticky_bits[2] <= True;
        if (signals[3]) sticky_bits[3] <= True;
        if (signals[4]) sticky_bits[4] <= True;
        if (signals[5]) sticky_bits[5] <= True;
        if (signals[6]) sticky_bits[6] <= True;
        if (signals[7]) sticky_bits[7] <= True;
    end
  end
endmodule

module ila_uart #(
    parameter WIDTH = 32,
    parameter DEPTH = 16,
    parameter CLK_FREQ = 50_000_000,
    parameter BAUD = 115200
)(
    input  logic              clk,
    input  logic              rst,

    input  logic [WIDTH-1:0]  signal_in,
    input  logic              trigger,

    output logic              uart_tx,
    output logic              busy
);

    // ----------------------------
    // Capture buffer
    // ----------------------------
    logic [WIDTH-1:0] buffer [0:DEPTH-1];
    logic [$clog2(DEPTH):0] wr_ptr;
    logic capturing, captured;

    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            wr_ptr    <= 0;
            capturing <= 0;
            captured  <= 0;
        end else begin
            if (trigger && !capturing && !captured) begin
                capturing <= 1;
                wr_ptr    <= 0;
            end

            if (capturing) begin
                buffer[wr_ptr] <= signal_in;
                wr_ptr <= wr_ptr + 1;

                if (wr_ptr == DEPTH-1) begin
                    capturing <= 0;
                    captured  <= 1;
                end
            end
        end
    end

    // ----------------------------
    // UART transmit FSM
    // ----------------------------
    typedef enum logic [3:0] {
        IDLE,
        SYNC1,
        SYNC1_WAIT,
        SYNC2,
        SYNC2_WAIT,
        LOAD_WORD,
        SEND_BYTE,
        WAIT_TX,
        NEXT_WORD,
        DONE
    } state_t;

    state_t state;

    logic [$clog2(DEPTH):0] rd_ptr;
    logic [WIDTH-1:0] current_word;
    logic [$clog2(WIDTH/8)-1:0] byte_idx;

    logic [7:0] uart_data;
    logic       uart_start;
    logic       uart_ready;

    assign busy = (state != IDLE);

    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            state       <= IDLE;
            rd_ptr      <= 0;
            byte_idx    <= 0;
            uart_start  <= 0;
        end else begin
            uart_start <= 0; // default (pulse)

            case (state)
                //--------------------------------------------------
                // IDLE
                //--------------------------------------------------
                IDLE: begin
                    if (captured) begin
                        state <= SYNC1;
                    end
                end

                //--------------------------------------------------
                // Send sync word: 0xAA 0x55
                //--------------------------------------------------
                SYNC1: begin
                    if (uart_ready) begin
                        uart_data  <= 8'hAA;
                        uart_start <= 1;
                        state      <= SYNC1_WAIT;
                    end
                end

                SYNC1_WAIT: begin
                    if (uart_ready) begin
                        state <= SYNC2;
                    end
                end

                SYNC2: begin
                    if (uart_ready) begin
                        uart_data  <= 8'h55;
                        uart_start <= 1;
                        state      <= SYNC2_WAIT;
                    end
                end

                SYNC2_WAIT: begin
                    if (uart_ready) begin
                        rd_ptr <= 0;
                        state  <= LOAD_WORD;
                    end
                end

                //--------------------------------------------------
                // Send captured data
                //--------------------------------------------------
                LOAD_WORD: begin
                    current_word <= buffer[rd_ptr];
                    byte_idx     <= 0;
                    state        <= SEND_BYTE;
                end

                SEND_BYTE: begin
                    if (uart_ready) begin
                        uart_data   <= current_word[7:0]; // LSB first
                        current_word <= current_word >> 8;
                        uart_start  <= 1;
                        state       <= WAIT_TX;
                    end
                end

                WAIT_TX: begin
                    if (uart_ready) begin
                        if (byte_idx == (WIDTH/8 - 1)) begin
                            state <= NEXT_WORD;
                        end else begin
                            byte_idx <= byte_idx + 1;
                            state    <= SEND_BYTE;
                        end
                    end
                end

                NEXT_WORD: begin
                    if (rd_ptr == DEPTH-1) begin
                        state <= DONE;
                    end else begin
                        rd_ptr <= rd_ptr + 1;
                        state  <= LOAD_WORD;
                    end
                end

                DONE: begin
                    // optional: clear captured to allow retrigger
                    // captured <= 0;  (move to sequential block if desired)
                    state <= IDLE;
                end
            endcase
        end
    end

    // ----------------------------
    // UART TX
    // ----------------------------
    uart_tx #(
        .CLK_FREQ(CLK_FREQ),
        .BAUD(BAUD)
    ) uart_inst (
        .clk(clk),
        .rst(rst),
        .data(uart_data),
        .start(uart_start),
        .tx(uart_tx),
        .ready(uart_ready)
    );

endmodule

module uart_tx #(
    parameter CLK_FREQ = 50_000_000,
    parameter BAUD     = 115200
)(
    input  logic       clk,
    input  logic       rst,

    input  logic [7:0] data,
    input  logic       start,

    output logic       tx,
    output logic       ready
);

    localparam CLKS_PER_BIT = CLK_FREQ / BAUD;

    typedef enum logic [2:0] {
        IDLE,
        START_BIT,
        DATA_BITS,
        STOP_BIT
    } state_t;

    state_t state;

    logic [15:0] clk_cnt;
    logic [2:0]  bit_idx;
    logic [7:0]  data_reg;

    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            state   <= IDLE;
            tx      <= 1;
            ready   <= 1;
            clk_cnt <= 0;
            bit_idx <= 0;
        end else begin
            case (state)
                IDLE: begin
                    tx    <= 1;
                    ready <= 1;
                    if (start) begin
                        ready   <= 0;
                        data_reg <= data;
                        clk_cnt <= 0;
                        state   <= START_BIT;
                    end
                end

                START_BIT: begin
                    tx <= 0;
                    if (clk_cnt == CLKS_PER_BIT-1) begin
                        clk_cnt <= 0;
                        state   <= DATA_BITS;
                        bit_idx <= 0;
                    end else begin
                        clk_cnt <= clk_cnt + 1;
                    end
                end

                DATA_BITS: begin
                    tx <= data_reg[bit_idx];
                    if (clk_cnt == CLKS_PER_BIT-1) begin
                        clk_cnt <= 0;
                        if (bit_idx == 7) begin
                            state <= STOP_BIT;
                        end else begin
                            bit_idx <= bit_idx + 1;
                        end
                    end else begin
                        clk_cnt <= clk_cnt + 1;
                    end
                end

                STOP_BIT: begin
                    tx <= 1;
                    if (clk_cnt == CLKS_PER_BIT-1) begin
                        state   <= IDLE;
                        ready   <= 1;
                        clk_cnt <= 0;
                    end else begin
                        clk_cnt <= clk_cnt + 1;
                    end
                end
            endcase
        end
    end

endmodule

module SystemDemo (
    input wire external_clk_25MHz,
    input wire [6:0] btn,
    output wire [7:0] led,
    output wire [3:0] gpdi_dp,
`ifdef HDMI_640
    output wire [3:0] gpdi_dn,
`endif
    inout wire  usb_fpga_bd_dn,
    inout wire  usb_fpga_bd_dp,
    output wire ftdi_rxd, // from FPGA to host
    inout wire gpdi_sda,
    output wire gpdi_scl

    // input wire jtag_tck,
    // input wire jtag_tms,
    // input wire jtag_tdi,
    // output wire jtag_tdo
);

  // JtagScanChain jtag (.jtag_tck, .jtag_tms, .jtag_tdi, .jtag_tdo, .in0(32'hABCD));

  // NB: btn[0] is active-low: it sends 1 when not pressed, and 0 when pressed
  wire rst_n;
`ifdef SYNTHESIS
  wire [30:0] ignore;
  debouncer #(.NIN(1)) db (
      .i_clk(clk_proc),
      .i_in(btn[0]),
      .o_debounced(rst_n),
      .o_debug(ignore)
  );
`else
  assign rst_n = btn[0];
`endif

  localparam bit True = 1'b1;
//   localparam bit False = 1'b0;
  wire clk_25MHz, clk_125MHz, clk_12MHz, clk_proc, clk_locked, demo_clocks_locked;

`ifdef SYNTHESIS
  MyClockGen clock_gen (
    .input_clk_25MHz(external_clk_25MHz),
    .clk_proc(clk_proc),
    .locked(clk_locked)
  );

  DemoClockGen demo_clock_gen (
    .input_clk_25MHz(external_clk_25MHz),
    .locked(demo_clocks_locked),
    .clk_125MHz(clk_125MHz),
    .clk_25MHz(clk_25MHz),
    .clk_12MHz(clk_12MHz)
  );
`else
    assign clk_25MHz  = external_clk_25MHz;
    assign clk_proc   = external_clk_25MHz;
    assign clk_125MHz = external_clk_25MHz;
    assign clk_locked = True;
`endif
  wire rst = !rst_n || !clk_locked || !demo_clocks_locked;

  axil_if axi_data_cache ();
  axil_if axi_data_mmap ();
  axil_if axi_insn_cache ();
  // memory is dual-ported, to connect to both I$ and D$
  axil_if axi_mem_a ();
  axil_if axi_mem_b ();

//   wire ila_busy;
//   // NB: must be declared after axi_data_mmap SV interface
//   wire [95:0] trace_data = {
//     axi_data_mmap.subord.AWADDR,
//     axi_data_mmap.subord.WDATA,

//     4'b1011,
//     axi_data_mmap.subord.AWVALID,
//     axi_data_mmap.subord.AWREADY,
//     axi_data_mmap.subord.WVALID,
//     axi_data_mmap.subord.WREADY,
//     axi_data_mmap.subord.WSTRB,
//     axi_data_mmap.subord.BREADY,
//     axi_data_mmap.subord.BVALID,
//     4'b1101,

//     14'd0 // padding to 32b
//   };
//   ila_uart #(
//     .WIDTH(96),
//     .DEPTH(64),
//     .CLK_FREQ(16_030_000),
//     .BAUD(115200)
// ) ila (
//     .clk(clk_proc),
//     .rst(rst),

//     .signal_in(trace_data),

//     // optional trigger (start capture)
//     .trigger(~rst),

//     .uart_tx(ftdi_rxd),
//     .busy(ila_busy)
// );

  EasyAxilMemory #(
    .OPT_SKIDBUFFER(1),
    .OPT_LOWPOWER(0),
`ifdef FULL_SIZE_MEM
    .NUM_WORDS(8192)
`else
    .NUM_WORDS(512)
`endif
  ) the_mem (
      .ACLK(clk_proc),
      .ARESETn(~rst),
      .port_ro(axi_mem_a.subord),
      .port_rw(axi_mem_b.subord)
  );

`ifdef HDMI_1280
  wire [3:0] gpdi_dn;
`endif
`ifdef HDMI_800
  wire [3:0] gpdi_dn;
`endif

  MemoryMap mmap (
      .ACLK(clk_proc),
      .ARESETn(~rst),
      .proc(axi_data_mmap.subord),
      .cache(axi_mem_b.manager),
      .clk_25MHz(clk_25MHz),
      .clk_12MHz,
      .clk_125MHz(clk_125MHz),
      .clk_locked(clk_locked),
      .btn(btn),
      .led(led),
      .gpdi_dp(gpdi_dp),
      .gpdi_dn(gpdi_dn),
      .usb_fpga_bd_dn(usb_fpga_bd_dn),
      .usb_fpga_bd_dp(usb_fpga_bd_dp)
  );

  wire halt;

  wire [`REG_SIZE] trace_pc;
  wire [`INSN_SIZE] trace_insn;
  cycle_status_e ignore2;

  DatapathPipelinedAxil datapath (
      .clk(clk_proc),
      .rst(rst),
      .imem(axi_mem_a.manager),
      .dmem(axi_data_mmap.manager),
      .halt(halt),
      .trace_completed_pc(trace_pc),
      .trace_completed_insn(trace_insn),
      .trace_completed_cycle_status(ignore2)
  );

endmodule

module SystemSim (
    input wire external_clk_25MHz,
    input wire rst,
    input wire [6:0] btn,
    output wire [7:0] led,
    output wire [3:0] gpdi_dp,
    output wire [3:0] gpdi_dn,
    inout wire  usb_fpga_bd_dn,
    inout wire  usb_fpga_bd_dp,
    output wire ftdi_rxd // from FPGA to host
);

  localparam bit True = 1'b1;
//   localparam bit False = 1'b0;
  wire clk_25MHz, clk_125MHz, clk_12MHz, clk_proc, clk_locked;

  assign clk_25MHz  = external_clk_25MHz;
  assign clk_12MHz  = external_clk_25MHz;
  assign clk_proc   = external_clk_25MHz;
  assign clk_125MHz = external_clk_25MHz;
  assign clk_locked = True;

  axil_if axi_data_cache ();
  axil_if axi_data_mmap ();
  axil_if axi_insn_cache ();
  // memory is dual-ported, to connect to both I$ and D$
  axil_if axi_mem_a ();
  axil_if axi_mem_b ();

  wire [7:0] fake_led, fake_led2;

`ifdef FULL_SIZE_MEM
  AxilMemory #(.NUM_WORDS(8192)) the_mem
`else
  AxilMemory #(.NUM_WORDS(2048)) the_mem
`endif
  (
      .ACLK(clk_proc),
      .ARESETn(~rst),
      .port_ro(axi_mem_a.subord),
      .port_rw(axi_mem_b.subord)
  );

  MemoryMap mmap (
      .ACLK(clk_proc),
      .ARESETn(~rst),
      .proc(axi_data_mmap.subord),
      .cache(axi_data_cache.manager),
      .clk_25MHz(clk_25MHz),
      .clk_12MHz,
      .clk_125MHz(clk_125MHz),
      .clk_locked(clk_locked),
      .btn(btn),
      .led(fake_led),
      .gpdi_dp(gpdi_dp),
      .gpdi_dn(gpdi_dn),
      .usb_fpga_bd_dn(usb_fpga_bd_dn),
      .usb_fpga_bd_dp(usb_fpga_bd_dp)
  );

  AxilCache #(
      .BLOCK_SIZE_BITS(32),
      .NUM_SETS(16)
      // .BLOCKS_PER_WAY(16)
  ) icache (
      .ACLK(clk_proc),
      .ARESETn(~rst),
      .proc(axi_insn_cache.subord),
      .mem(axi_mem_a.manager)
  );

  AxilCache #(
      .BLOCK_SIZE_BITS(32),
      .NUM_SETS(16)
      // .BLOCKS_PER_WAY(16)
  ) dcache (
      .ACLK(clk_proc),
      .ARESETn(~rst),
      .proc(axi_data_cache.subord),
      .mem(axi_mem_b.manager)
  );

  wire halt;
  wire [`REG_SIZE] trace_writeback_pc;
  wire [`INSN_SIZE] trace_writeback_insn;
  wire cycle_status_e trace_writeback_cycle_status;

  // localparam int MmapButtons   = 32'hFF00_1000;
  localparam int MmapLeds      = 32'hFF00_2000;
  //localparam int MmapUartRead    = 32'hFF00_3000;
  //localparam int MmapUartWrite    = 32'hFF00_3001;
  // localparam int MmapUsb       = 32'hFF00_4000;
  // localparam int MmapRng       = 32'hFF00_5000;
  localparam int MmapDisplayStart = 32'hFF10_0000;
  `ifdef FULL_SIZE_FRAME_BUFFER
  localparam bit[9:0] DisplayWidth = 320;
  localparam bit[9:0] DisplayHeight = 240;
  `else
  localparam bit[9:0] DisplayWidth = 40;
  localparam bit[9:0] DisplayHeight = 30;
  `endif
  localparam int DisplayPixels = DisplayHeight * DisplayWidth;
  localparam int DisplayPixelSizeBits = 8;
  // localparam bit[9:0] DisplayFrameBufferScale = 640 / DisplayWidth;
  // localparam int DisplayFrameBufferScaleShift = $clog2(DisplayFrameBufferScale);
  localparam int MmapDisplayEnd = MmapDisplayStart + (DisplayPixels * (DisplayPixelSizeBits / 8));

  wire is_write_to_read_only = axi_data_cache.manager.AWVALID &&
        axi_data_cache.manager.AWADDR[14:0] <= 15'h6000 &&
        axi_data_cache.manager.AWADDR != MmapLeds &&
        (axi_data_cache.manager.AWADDR < MmapDisplayStart || axi_data_cache.manager.AWADDR > MmapDisplayEnd);

  DatapathPipelinedCache datapath (
      .clk(clk_proc),
      .rst(rst),
      .icache(axi_insn_cache.manager),
      .dcache(axi_data_mmap.manager),
      // .dcache(axi_data_cache.manager),
      .halt(halt),
      .trace_writeback_pc(trace_writeback_pc),
      .trace_writeback_insn(trace_writeback_insn),
      .trace_writeback_cycle_status(trace_writeback_cycle_status)
  );

endmodule
