# source verilog files
SYNTH_SOURCES=divider_unsigned.sv
TOP_SYNTH_MODULE=divider

# testbench files
TESTBENCH=dummy.sv
TOP_TESTBENCH_MODULE=dummy

# zip file that gets uploaded
#ZIP_SOURCES=rca.sv output/rca4.bit
#ZIP_FILE=rca.zip

# implementation files
#IMPL_SOURCES=$(SYNTH_SOURCES)
#TOP_IMPL_MODULE=rca4
#CONSTRAINTS=lab1.xdc 
#BITSTREAM_FILENAME=rca4.bit

include ../common/make/vivado.mk
